---
all:
  hosts:
    el-instance:
      ansible_host: 192.168.31.239
    ki-instance:
      ansible_host: 192.168.31.238
  vars:
    ansible_connection: ssh
    ansible_user: ubuntu
    ansible_ssh_pass: ubuntu
elasticsearch:
  hosts:
    el-instance:
kibana:
  hosts:
    ki-instance: